version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:3001"
    restart: on-failure 
    env_file:
      - ./backend/.env
    networks:
      - app-network
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    networks:
      - app-network

  database:
    image: postgres:latest
    ports:
      - "5432"
    env_file:
      - ./backend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
